name: 自动构建并提交到 Github 与 Nuget

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: 安装 .NET 8.0 环境
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'
    - name: 还原依赖库
      run: dotnet restore
    - name: 构建
      run: dotnet build --no-restore -c Release
    - name: 测试
      run: dotnet test --no-build -c Release
    - name: 构建 NuGet 包
      run: dotnet pack --no-build -c Release -o nupkg
    - name: 列出 NuGet 包文件
      run: dir nupkg
    - name: 获取 NuGet 包版本
      id: get_version
      shell: pwsh
      run: |
        $version = (Select-String -Path nupkg/*.nupkg -Pattern "\d+\.\d+\.\d+" | Select-Object -First 1).Matches.Value
        echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
    - name: 上传构建工件
      uses: actions/upload-artifact@v3
      with:
        name: nupkg
        path: nupkg/*.nupkg

  publish:
    needs: build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: 安装 .NET 8.0 环境
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'
    - name: 下载构建工件
      uses: actions/download-artifact@v3
      with:
        name: nupkg
        path: nupkg
    - name: 列出 NuGet 包文件
      run: dir nupkg
    - name: 推送至 Github NuGet
      run: dotnet nuget push "nupkg/*.nupkg" --source "https://nuget.pkg.github.com/Ink-Marks-Studio/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: 推送至 NuGet.org
      run: dotnet nuget push "nupkg/*.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json

  release:
    needs: publish
    runs-on: ubuntu-latest
    steps:
    - name: 创建 GitHub 发布
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.VERSION }}
        release_name: Release v${{ env.VERSION }}
        draft: false
        prerelease: false
        body: |
          自动构建
